M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu18.04.1} date ti  6. syyskuuta 2022 13.01.26
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-06T13:01:26+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu18.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X-0.4673Y0.2143
X0.4776Y0.2143
T0
M30
